### ISSUE TITLE
Incompatibility between espgen output and pyresp_gen.py 

### ISSUE THREAD

**Issue by SerpentByte** [csu1505110121/pyresp_gen#5]
- Ambertools==23.3

the commands we are using are:
```
espgen -i run.out -o run.dat -p 1
pyresp_gen.py -i run.dat -f1 1.in -f2 2.in -p chg -q -2
```

where run.out is the Gaussian (16) log file and run.dat is the esp file generated by espgen.

pyresp_gen.py fails with the following error:
```index 0 is out of bounds for axis 0 with size 0```

It does not generate 1.in or 2.in. It generated RESPIN1 and RESPIN2. However pyresp.py does not recognize them.
[pyresp_files.zip](https://github.com/csu1505110121/pyresp_gen/files/15011536/pyresp_files.zip)

**Comment by csu1505110121** [comment]
Two issues exist:
1. The file you input are complex instead of single molecule, although `pyresp_gen` could handle complex molecules. I do not know the purpose of your project. However, you should be careful about this;
2. When going through your `dat` file generated by espgen. The element number (4th column, line 2 to 96) are all zero. It looks werid. When I manually corrected them (see attached file), `pyresp_gen` could run normally. As I mentioned in this tutorial (https://csu1505110121.github.io/tutorial/2023/02/16/pyresp_gen_tutorial.html), latest`espgen` (at least AMBER 2018) may have some issues, not testing that on Amber 2023 or later version.
[pyresp_files_QZ.zip](https://github.com/csu1505110121/pyresp_gen/files/15014983/pyresp_files_QZ.zip)
